export const categories = [
  {
    id: 1,
    name: "Electronics",
    description: "Category for electronic devices",
    type: "Product",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 2,
    name: "Clothing",
    description: "Category for clothing items",
    type: "Product",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 3,
    name: "Books",
    description: "Category for books",
    type: "Product",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 4,
    name: "Furniture",
    description: "Category for furniture items",
    type: "Product",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 5,
    name: "Home Appliances",
    description: "Category for home appliances",
    type: "Product",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 6,
    name: "Sports Equipment",
    description: "Category for sports equipment",
    type: "Product",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 7,
    name: "Beauty Products",
    description: "Category for beauty products",
    type: "Product",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 8,
    name: "Groceries",
    description: "Category for grocery items",
    type: "Product",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 9,
    name: "Toys",
    description: "Category for toys",
    type: "Product",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 10,
    name: "Pet Supplies",
    description: "Category for pet supplies",
    type: "Product",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 11,
    name: "Health & Wellness",
    description: "Category for health and wellness products",
    type: "Product",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 12,
    name: "Automotive",
    description: "Category for automotive products",
    type: "Product",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 13,
    name: "Office Supplies",
    description: "Category for office supplies",
    type: "Product",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 14,
    name: "Jewelry",
    description: "Category for jewelry items",
    type: "Product",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 15,
    name: "Garden & Outdoor",
    description: "Category for garden and outdoor products",
    type: "Product",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 16,
    name: "Movies & Music",
    description: "Category for movies and music",
    type: "Product",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 17,
    name: "Travel",
    description: "Category for travel accessories",
    type: "Product",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 18,
    name: "Art & Craft",
    description: "Category for art and craft supplies",
    type: "Product",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 19,
    name: "Baby & Kids",
    description: "Category for baby and kids' products",
    type: "Product",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 20,
    name: "Electrical",
    description: "Category for electrical supplies",
    type: "Product",
    created_at: new Date(),
    updated_at: new Date(),
  },
];
