export const incomes = [
  {
    id: 1,
    item: "Salary",
    category: "Income",
    transaction_date: new Date(),
    description: "Monthly salary payment",
    amount: 5000,
    units: "USD",
    total: 5000,
    created_at: new Date(),
    updated_at: new Date(),
    deleted_at: null,
  },
  {
    id: 2,
    item: "Freelance Project",
    category: "Income",
    transaction_date: new Date(),
    description: "Payment for freelance work",
    amount: 1000,
    units: "USD",
    total: 1000,
    created_at: new Date(),
    updated_at: new Date(),
    deleted_at: null,
  },
  {
    id: 3,
    item: "Dividends",
    category: "Investment",
    transaction_date: new Date(),
    description: "Dividend income from investments",
    amount: 200,
    units: "USD",
    total: 200,
    created_at: new Date(),
    updated_at: new Date(),
    deleted_at: null,
  },
  {
    id: 4,
    item: "Rent",
    category: "Income",
    transaction_date: new Date(),
    description: "Rental income from property",
    amount: 1500,
    units: "USD",
    total: 1500,
    created_at: new Date(),
    updated_at: new Date(),
    deleted_at: null,
  },
  {
    id: 5,
    item: "Bonus",
    category: "Income",
    transaction_date: new Date(),
    description: "Year-end bonus payment",
    amount: 3000,
    units: "USD",
    total: 3000,
    created_at: new Date(),
    updated_at: new Date(),
    deleted_at: null,
  },
  {
    id: 6,
    item: "Interest",
    category: "Income",
    transaction_date: new Date(),
    description: "Interest income from savings account",
    amount: 50,
    units: "USD",
    total: 50,
    created_at: new Date(),
    updated_at: new Date(),
    deleted_at: null,
  },
  {
    id: 7,
    item: "Consulting Fee",
    category: "Income",
    transaction_date: new Date(),
    description: "Payment for consulting services",
    amount: 800,
    units: "USD",
    total: 800,
    created_at: new Date(),
    updated_at: new Date(),
    deleted_at: null,
  },
  {
    id: 8,
    item: "Stock Dividends",
    category: "Investment",
    transaction_date: new Date(),
    description: "Dividend income from stock investments",
    amount: 500,
    units: "USD",
    total: 500,
    created_at: new Date(),
    updated_at: new Date(),
    deleted_at: null,
  },
  {
    id: 9,
    item: "Side Hustle",
    category: "Income",
    transaction_date: new Date(),
    description: "Payment for side hustle project",
    amount: 700,
    units: "USD",
    total: 700,
    created_at: new Date(),
    updated_at: new Date(),
    deleted_at: null,
  },
  {
    id: 10,
    item: "Gift",
    category: "Income",
    transaction_date: new Date(),
    description: "Gift received",
    amount: 100,
    units: "USD",
    total: 100,
    created_at: new Date(),
    updated_at: new Date(),
    deleted_at: null,
  },
];
